services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: tahira
      POSTGRES_PASSWORD: gis123
      POSTGRES_DB: osmdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
